version: "3.9"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9393"
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputFile:/csvserver/inputdata

    

